{
 "title": "CCX",
 "description": "General overview of CCX",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "$namespace CCX Helm Charts Versions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (last_over_time(helm_chart_info{namespace=\"$namespace\", exported_cluster=\"$cluster\"})) by (chart, version)",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "CMON UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(cmon_up{kubernetes_namespace=~\"$namespace\", exported_cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Datastores UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(cmon_cluster_up{kubernetes_namespace=~\"$namespace\", exported_cluster=~\"$cluster\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Datastores DOWN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(cmon_cluster_up{kubernetes_namespace=~\"$namespace\", exported_cluster=~\"$cluster\"} == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container CPU usage %",
   "type": "timeseries",
   "description": "1 minute average",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", image!=\"\", exported_cluster=\"$cluster\"}[1m])) by (container) * 100",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Container MEM usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", image!=\"\", exported_cluster=\"$cluster\"}) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Datastores",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cmon_cluster_up{kubernetes_namespace=~\"$namespace\", exported_cluster=~\"$cluster\"}",
     "legendFormat": "{{ ClusterName }}"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "filters": "environment=$namespace, exported_cluster=$cluster"
    }
   ]
  },
  {
   "title": "Deployments $namespace $cluster",
   "type": "gauge",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=~\"$namespace\", exported_cluster=~\"$cluster\"} / kube_deployment_status_replicas{namespace=~\"$namespace\", exported_cluster=~\"$cluster\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  }
 ]
}