{{ if .Values.createDatabases }}
{{- $pgClusterName := "acid-ccx" }}
kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "acid-ccx"

spec:
  teamId: "acid"
  postgresql:
    version: "14"
    parameters:
      wal_level: logical
      max_replication_slots: "10"
      max_wal_senders: "10"
      max_worker_processes: "20"
  numberOfInstances: {{ .Values.postgresql.replicas | default 1 }}
  volume:
    size: {{ .Values.postgresql.volumeSize | default "10Gi" }}
    {{- with .Values.postgresql.storageClass  }}
    storageClass: {{ . }}
    {{- end }}
  users:
    ccx:
      - superuser
      - createdb
  databases:
    ccx: ccx
    ccx_deployer: ccx
    ccx_backup: ccx
    ccx_vpc: ccx
    ccx_keycloak: ccx

  patroni:
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"
    pg_hba:
      - local all all trust
      - local replication all trust
      - host  all all all md5
      - host  replication all all md5

  resources:
    requests:
      cpu: {{ dig "resources" "requests" "cpu" "100m" .Values.postgresql }}
      memory: {{ dig "resources" "requests" "memory" "100Mi" .Values.postgresql }}
    limits:
      cpu: {{ dig "resources" "limits" "cpu" "500m" .Values.postgresql }}
      memory: {{ dig "resources" "limits" "memory" "500Mi" .Values.postgresql }}
  {{- with .Values.postgresql.clone }}
  clone:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  enableLogicalBackup: {{ .Values.postgresql.enableLogicalBackup | default false }}
  {{- if (dig "metrics" "enabled" false .Values.postgresql) }}
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
  sidecars:
  - name: postgres-exporter
    image: {{ required "postgresql.metrics.image is required when postgresql.metrics.enabled is true" (dig "metrics" "image" "" .Values.postgresql) }}
    ports:
    - name: metrics
      containerPort: 9187
    env:
    - name: DATA_SOURCE_URI
      value: "localhost:5432/postgres?sslmode=disable"
    - name: DATA_SOURCE_USER
      valueFrom:
        secretKeyRef:
          name: postgres.{{ $pgClusterName }}.credentials.postgresql.acid.zalan.do
          key: username
    - name: DATA_SOURCE_PASS
      valueFrom:
        secretKeyRef:
          name: postgres.{{ $pgClusterName }}.credentials.postgresql.acid.zalan.do
          key: password
  {{- end }}
{{ end }}
