apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccx-rest-user-service
  labels:
    app: ccx-rest-user-service
    run: ccx-rest-user-service
spec:
  replicas: {{ .Values.ccx.services.rest_service.replicas | default 1 }}
  selector:
    matchLabels:
      app: ccx-rest-user-service
      run: ccx-rest-user-service
  template:
    metadata:
      labels:
        app: ccx-rest-user-service
        run: ccx-rest-user-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        checksum: {{ include (print $.Template.BasePath "/ccx/secrets.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/ccx/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: ccx-rest-user-service
          image: {{ .Values.ccx.services.rest_service.image | default .Values.ccx.backend.image | required "No image set for rest" }}
          command: ["/bin/ccx-rest", "serve"]
          env:
            - name: CONFIG_FILE
              value: "/conf/ccx.yaml"
            - name: PROMETHEUS_URL
              value: http://{{ include "ccx.prometheusHostname" . }}:9090
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- range $key, $val := .Values.ccx.services.rest_service.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          {{ if .Values.ccx.preferNewStores }}
            - name: PREFER_NEW_STORES
              value: "true"
          {{ end }}
          {{- range $key, $val := .Values.ccx.services.billing.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: ccx
            - secretRef:
                name: db
            {{ if not .Values.ccx.useK8sSecrets }}
            - secretRef:
                name: vault # userdb still needs this for now
            {{ end }}
            {{ if .Values.ccx.services.billing.stripe }}
            - secretRef:
                name: stripe
            {{ end }}
          ports:
            - name: service
              containerPort: 20001
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: "/conf"
          {{ if .Values.ccx.services.billing.stripe }}
            - name: prices-volume
              mountPath: /etc/prices.yaml
              subPath: prices.yaml
          {{ end }}
          resources:
            {{- toYaml .Values.ccx.services.rest_service.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: ccx-config-core
      {{ if .Values.ccx.services.billing.stripe }}
        - name: prices-volume
          configMap:
            name: prices
      {{ end }}
      {{ with .Values.ccx.services.rest_service.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.ccx.services.rest_service.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.ccx.services.rest_service.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: ccx-rest-user-svc
  labels:
    app: ccx-rest-user-service
    run: ccx-rest-user-service
spec:
  type: ClusterIP
  selector:
    app: ccx-rest-user-service
  ports:
    - protocol: TCP
      port: 20001
      targetPort: 20001
