apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccx-monitor-service
  labels:
    app: ccx-monitor-service
    run: ccx-monitor-service
spec:
  replicas: {{ .Values.ccx.services.monitor.replicas | default .Values.global.replicas }}
  selector:
    matchLabels:
      app: ccx-monitor-service
      run: ccx-monitor-service
  template:
    metadata:
      labels:
        app: ccx-monitor-service
        run: ccx-monitor-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        checksum: {{ include (print $.Template.BasePath "/ccx/secrets.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/ccx/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: ccx-monitor-service
          image: {{ .Values.ccx.services.monitor.image | default .Values.ccx.backend.image | required "No image set for monitor" }}
          command: ["/bin/ccx-monitor-service"]
          env:
            - name: SUPPORT_RECEIVERS
              value: {{ .Values.ccx.emailSupport }}
          {{- range $key, $val := .Values.ccx.services.monitor.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: ccx
            - secretRef:
                name: db
            {{ if not .Values.ccx.useK8sSecrets }}
            - secretRef:
                name: vault
            {{ end }}
          ports:
            - name: service
              containerPort: 18091
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          resources:
            {{- toYaml .Values.ccx.services.monitor.resources | nindent 12 }}
      {{ with .Values.ccx.services.monitor.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.ccx.services.monitor.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.ccx.services.monitor.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{ end }}
