{{ if not .Values.ccx.newWorld }}
{{- $script := (printf "%v" (.Files.Get "files/ccx_growfs.sh")) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ccx-growfs
data:
  ccx_growfs.sh: |-
{{ $script | indent 4 }}
{{end}}