{{- if .Values.fluentbit.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ccx-fluentbit-ingress
  annotations:
    {{ if .Values.ccx.ingress.ssl.clusterIssuer }}
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: {{ .Values.ccx.ingress.ssl.clusterIssuer }}
    {{ end }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /loki/$1
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: {{ .Values.ccx.ingress.ingressClassName | default "nginx" }}
  tls:
    - hosts:
        - {{ include "ccx.ccxFQDN" . }}
      secretName: {{ .Values.ccx.ingress.ssl.secretName | default "ccx-ingress-cert" }}
  rules:
    - host: {{ include "ccx.ccxFQDN" . }}
      http:
        paths:
          - path: /loki/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ccxdeps-loki-gateway
                port:
                  number: 80
          - path: /loki
            pathType: ImplementationSpecific
            backend:
              service:
                name: ccxdeps-loki-gateway
                port:
                  number: 80
{{- end }}