apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccx-auth-service
  labels:
    app: ccx-auth-service
    run: ccx-auth-service
spec:
  replicas: {{ .Values.ccx.services.auth.replicas | default .Values.global.replicas }}
  selector:
    matchLabels:
      app: ccx-auth-service
      run: ccx-auth-service
  template:
    metadata:
      labels:
        app: ccx-auth-service
        run: ccx-auth-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        checksum: {{ include (print $.Template.BasePath "/ccx/secrets.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/ccx/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: ccx-auth-service
          image: {{ .Values.ccx.services.auth.image | default .Values.ccx.backend.image | required "No image set for auth" }}
          command: ["/bin/ccx-auth-service"]
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: S9S_LICENSE_SERVER_URL
              value: "https://severalnines.com/service/lic.php"
            {{- if (include "ccx.KeycloakService" . ) }}
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ccx.KeycloakService" . }}
                  key: admin-password
            - name: KEYCLOAK_URL
              value: http://{{ include "ccx.KeycloakService" . }}/keycloak
            {{- end }}
          {{- range $key, $val := .Values.ccx.services.auth.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: ccx
            - secretRef:
                name: db
          ports:
            - name: service
              containerPort: 5050
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          resources:
            {{- toYaml .Values.ccx.services.auth.resources | nindent 12 }}
      {{ with .Values.ccx.services.auth.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.ccx.services.auth.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.ccx.services.auth.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{ end }}
