kind: Service
apiVersion: v1
metadata:
  name: ccx-ui-auth-svc
  labels:
    app: ccx-ui-auth
    run: ccx-ui-auth
spec:
  type: ClusterIP
  selector:
    app: ccx-ui-auth
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
