apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccx-ui-admin
  labels:
    run: ccx-ui-admin
    app: ccx-ui-admin
spec:
  replicas: {{ .Values.ccx.services.ccxUIAdmin.replicas | default 1 }}
  selector:
    matchLabels:
      app: ccx-ui-admin
      run: ccx-ui-admin
  template:
    metadata:
      labels:
        app: ccx-ui-admin
        run: ccx-ui-admin
    spec:
      containers:
        - name: ccx-ui-admin
          image: {{ .Values.ccx.services.ccxUIAdmin.image | required "No image set for ccxUIAdmin" }}
          env:
          {{- range $key, $val := .Values.ccx.services.ccxUIAdmin.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          ports:
            - name: service
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.ccx.services.ccxUIAdmin.resources | nindent 12 }}
      {{ with .Values.ccx.services.ccxUIAdmin.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.ccx.services.ccxUIAdmin.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.ccx.services.ccxUIAdmin.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{ end }}
