{{ if .Values.ccx.services.dispatcher.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ccx-dispatcher-service-svc
  labels:
    run: ccx-alertmgr-dispatcher
    app: ccx-alertmgr-dispatcher
spec:
  type: ClusterIP
  selector:
    app: ccx-alertmgr-dispatcher
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
{{ end }}
