{{ if .Values.ccx.oldWorld }}
apiVersion: v1
kind: Service
metadata:
  name: ccx-backup-storage-svc
  labels:
    app: ccx-backup-storage
    run: ccx-backup-storage
spec:
  type: ClusterIP
  selector:
    app: ccx-backup-storage
  ports:
    - protocol: TCP
      port: 19000
      targetPort: 19000
{{ end }}
