apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccx-hook-service
  labels:
    app: ccx-hook-service
    run: ccx-hook-service
spec:
  replicas: {{ .Values.ccx.services.hook.replicas | default .Values.global.replicas }}
  selector:
    matchLabels:
      app: ccx-hook-service
      run: ccx-hook-service
  template:
    metadata:
      labels:
        app: ccx-hook-service
        run: ccx-hook-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        checksum: {{ include (print $.Template.BasePath "/ccx/secrets.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/ccx/config.yaml") . | sha256sum }}
        checksum/ccx: {{ include (print $.Template.BasePath "/ccx/ccx-config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: ccx-hook-service
          image: {{ .Values.ccx.services.hook.image | default .Values.ccx.backend.image | required "No image set for hooks" }}
          command: ["/bin/ccx-hook-service"]
          env:
            - name: CONFIG_FILE
              value: "/conf/ccx.yaml"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- range $key, $val := .Values.ccx.services.hook.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: ccx
            - secretRef:
                name: db
          ports:
            - name: service
              containerPort: 19785
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: "/conf"
          resources:
            {{- toYaml .Values.ccx.services.hook.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: ccx-config
      {{ with .Values.ccx.services.hook.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.ccx.services.hook.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.ccx.services.hook.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{ end }}
