# old config file, left alone for now
apiVersion: v1
kind: ConfigMap
metadata:
  name: ccx-config
data:
  {{- with .Values.ccx.config }}
  ccx.yaml: |
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
# new config file, which embeds the old one, so that it can used alone
apiVersion: v1
kind: ConfigMap
metadata:
  name: ccx-config-core
data:
  ccx.yaml: |
    legacy:
      {{- with .Values.ccx.config }}
      {{- toYaml . | nindent 6 }}
      {{- end }}

    deployer:
      {{- if .Values.ccx.services.deployer.config }}
      {{- toYaml .Values.ccx.services.deployer.config | nindent 6 }}
      {{- else }}
      aws_vendor:
        regions:
          eu-north-1:
            image_id: ami-05baaef454dd96656
        database_vendors:
          - name: mariadb
            security_groups:
            {{- with include "ccx.cidr" . | fromJsonArray }}
            {{- range . }}
              - cidr: {{ . }}
                from_port: 1
                ip_protocol: tcp
                to_port: 65535
                self: true
            {{- end }}
            {{- end }}
          - name: microsoft
            security_groups:
            {{- with include "ccx.cidr" . | fromJsonArray }}
            {{- range . }}
              - cidr: {{ . }}
                from_port: 1
                ip_protocol: tcp
                to_port: 65535
                self: true
            {{- end }}
            {{- end }}
          - name: percona
            security_groups:
            {{- with include "ccx.cidr" . | fromJsonArray }}
            {{- range . }}
              - cidr: {{ . }}
                from_port: 1
                ip_protocol: tcp
                to_port: 65535
                self: true
            {{- end }}
            {{- end }}
          - name: postgres
            security_groups:
            {{- with include "ccx.cidr" . | fromJsonArray }}
            {{- range . }}
              - cidr: {{ . }}
                from_port: 1
                ip_protocol: tcp
                to_port: 65535
                self: true
            {{- end }}
            {{- end }}
          - name: redis
            security_groups:
            {{- with include "ccx.cidr" . | fromJsonArray }}
            {{- range . }}
              - cidr: {{ . }}
                from_port: 1
                ip_protocol: tcp
                to_port: 65535
                self: true
            {{- end }}
            {{- end }}
      {{- end }}
      copy_files:
        - target: "/home/ubuntu/ccx_growfs"
          source: "/conf/ccx_growfs.sh"
          perms: "0755"
      {{- if .Values.fluentbit.enabled }}
        - target: "/etc/fluent-bit/fluent-bit.conf"
          source: "/conf/fluent-bit.conf"
          owner: "root:root"
          perms: "0644"
        - target: "/etc/fluent-bit/parsers-multiline.conf"
          source: "/conf/parsers-multiline.conf"
          owner: "root:root"
          perms: "0644"
      {{- end }}
      {{- if and .Values.fluentbit.enabled .Values.fluentbit.extraOutputConfig }}
        - target: "/etc/fluent-bit/extra_output.conf"
          source: "/conf/extra_output.conf"
          owner: "root:root"
          perms: "0644"
      {{- end }}
      {{- range .Values.ccx.services.deployer.extraCopyFiles }}
        - target: {{ .target }}
          source: {{ .source }}
          owner: {{ .owner }}
          perms: {{ .perms }}
      {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ccx-config-growfs
data:
  # lvm script NB don't indent the template, something odd happens re. #!
  {{- $ccx_growfs_sh := (printf "%v" (.Files.Get "files/ccx_growfs.sh")) }}
  ccx_growfs.sh: |-
{{ $ccx_growfs_sh | indent 4 }}
