apiVersion: batch/v1
kind: Job
metadata:
  name: ccx-check-certificate-authority
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "555"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 432000
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: check-certificate-authority
          image: {{ .Values.ccx.services.stores_service.image | default .Values.ccx.backend.image | required "No image set for stores" }}
          command: ["/bin/ccx-stores", "check-certificate-authority"]
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      {{- with .Values.ccx.services.stores_service.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ccx.services.stores_service.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ccx.services.stores_service.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
