apiVersion: v1
kind: Service
metadata:
  name: ccx-ui-app-svc
  labels:
    app: ccx-ui-app
    run: ccx-ui-app
spec:
  type: ClusterIP
  selector:
    app: ccx-ui-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
