apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccx-user
  labels:
    app: ccx-user
    run: ccx-user
spec:
  replicas: {{ .Values.ccx.services.user.replicas | default .Values.global.replicas }}
  selector:
    matchLabels:
      app: ccx-user
      run: ccx-user
  template:
    metadata:
      labels:
        app: ccx-user
        run: ccx-user
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        checksum: {{ include (print $.Template.BasePath "/ccx/secrets.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/ccx/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: ccx-user
          image: {{ .Values.ccx.services.user.image | default .Values.ccx.backend.image | required "No image set for users" }}
          command: ["/bin/ccx-users"]
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- range $key, $val := .Values.ccx.services.auth.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          {{- range $key, $val := .Values.ccx.services.user.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: ccx
            - secretRef:
                name: admin-users
            - secretRef:
                name: db
          ports:
            - name: service
              containerPort: 3030
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          resources:
            {{- toYaml .Values.ccx.services.user.resources | nindent 12 }}
      {{ with .Values.ccx.services.user.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.ccx.services.user.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.ccx.services.user.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{ end }}
