apiVersion: v1
kind: Service
metadata:
  name: ccx-monitor-service-svc
  labels:
    app: ccx-monitor-service
    run: ccx-monitor-service
spec:
  type: ClusterIP
  selector:
    app: ccx-monitor-service
  ports:
    - protocol: TCP
      port: 18091
      targetPort: 18091
