apiVersion: v1
kind: Service
metadata:
  name: ccx-hook-service-svc
  labels:
    app: ccx-hook-service
    run: ccx-hook-service
spec:
  type: ClusterIP
  selector:
    app: ccx-hook-service
  ports:
    - protocol: TCP
      port: 19785
      targetPort: 19785
