apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccx-state-worker
  labels:
    app: ccx-state-worker
    run: ccx-state-worker
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ccx-state-worker
      run: ccx-state-worker
  template:
    metadata:
      labels:
        app: ccx-state-worker
        run: ccx-state-worker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        checksum: {{ include (print $.Template.BasePath "/ccx/secrets.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/ccx/config.yaml") . | sha256sum }}
        checksum/ccx: {{ include (print $.Template.BasePath "/ccx/ccx-config.yaml") . | sha256sum }}
    spec:
      {{- if .Values.ccx.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.ccx.imagePullSecret }}
      {{- end }}
      containers:
        - name: state-worker
          image: {{ .Values.ccx.services.stores_service.image | default .Values.ccx.backend.image | required "No image set for stores" }}
          command: ["/bin/ccx-stores", "work"]
          env:
            - name: CONFIG_FILE
              value: "/conf/ccx.yaml"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: BACKUPS_DB_DSN
              valueFrom:
                secretKeyRef:
                  name: db-backup
                  key: DB_DSN
            - name: DEPLOYER_DB_DSN
              valueFrom:
                secretKeyRef:
                  name: db-deployer
                  key: DB_DSN
            - name: VPCS_DB_DSN
              valueFrom:
                secretKeyRef:
                  name: db-vpc
                  key: DB_DSN
            - name: INGRESS_ANNOTATIONS
              value: |
                {{- $annotations := dict }}
                {{- if .Values.ccx.ingress.ssl.clusterIssuer }}
                {{- $_ := set $annotations "kubernetes.io/tls-acme" "true" }}
                {{- $_ := set $annotations "cert-manager.io/cluster-issuer" .Values.ccx.ingress.ssl.clusterIssuer }}
                {{- end }}
                {{- with .Values.ccx.ingress.annotations }}
                {{- $_ := merge $annotations . }}
                {{- end }}
                {{ $annotations | toJson }}
          {{- range $key, $val := .Values.ccx.services.stores_service.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          {{- range $key, $val := .Values.ccx.services.backupstorage.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          {{- range $key, $val := .Values.ccx.services.datastorestorage.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          {{- range $key, $val := .Values.ccx.services.deployer.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          {{- if .Values.ccx.services.datastorestorage.workInterval }}
            - name: WORK_INTERVAL
              value : {{ .Values.ccx.services.datastorestorage.workInterval | quote }}
          {{- end }}
          {{- if .Values.ccx.autoRepair.enabled }}
            - name: AUTO_REPAIR_ENABLED
              value : "true"
            - name: AUTO_REPAIR_AFTER
              value : {{ .Values.ccx.autoRepair.delay | quote }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: ccx
            - secretRef:
                name: cmon-credentials
            - secretRef:
                name: db
          {{- range $name := .Values.ccx.cloudSecrets }}
            - secretRef:
                name: {{ $name }}
          {{- end }}
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: conf-core
              mountPath: "/conf/ccx.yaml"
              subPath: "ccx.yaml"
          resources:
            {{- toYaml .Values.ccx.services.datastorestorage.resources | nindent 12 }}
      volumes:
        - name: conf-core
          configMap:
            name: ccx-config-core
      {{ with .Values.ccx.services.datastorestorage.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.ccx.services.datastorestorage.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.ccx.services.datastorestorage.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{ end }}
