{{- if and .Values.ccx.useK8sSecrets .Values.ccx.vault.addr }}
apiVersion: batch/v1
kind: Job
metadata:
  name: ccx-migrate-secrets
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "777"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 432000
  template:
    spec:
    {{- with .Values.ccx.services.migrate.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.ccx.services.migrate.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.ccx.services.migrate.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: migrate-secrets
          image: {{ .Values.ccx.services.migrate.image | default .Values.ccx.backend.image |  required "migrate image is missing" }}
          command: ["/bin/ccx-migrate-secrets"]
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - secretRef:
                name: db
            - secretRef:
                name: vault
      restartPolicy: Never
{{- end }}