{{ if .Values.ccx.oldWorld }}
apiVersion: v1
kind: Service
metadata:
  name: ccx-controller-storage-svc
  labels:
    app: ccx-controller-storage
    run: ccx-controller-storage
spec:
  type: ClusterIP
  selector:
    app: ccx-controller-storage
  ports:
    - protocol: TCP
      port: 19002
      targetPort: 19002
{{ end }}
