apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccx-ui-auth
  labels:
    app: ccx-ui-auth
    run: ccx-ui-auth
spec:
  replicas: {{ .Values.ccx.services.uiauth.replicas | default 1 }}
  selector:
    matchLabels:
      app: ccx-ui-auth
  template:
    metadata:
      labels:
        app: ccx-ui-auth
    spec:
      containers:
        - name: ccx-ui-auth
          image: {{ .Values.ccx.services.uiauth.image | required ".Values.ccx.services.uiauth.image is missing" }}
          env:
          {{- range $key, $val := .Values.ccx.services.uiauth.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
            - name: FE_BASE_DOMAIN
              value: "{{ include "ccx.sessionDomain" . }}"
            - name: FE_REACT_APP_CCX_URL
              value: "https://{{ include "ccx.ccxFQDN" .}}"
            - name: FE_REACT_APP_CCX_ADMIN_REDIRECT_PATH
              value: "https://{{ include "ccx.ccxFQDN" .}}/admin"
            - name: FE_REACT_APP_CURRENT_APP
              value: ccx
            - name: FE_REACT_APP_USER_AUTH_SERVICE_URL
              value: /api/auth
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.ccx.services.uiauth.resources | nindent 12 }}
      {{ with .Values.ccx.services.uiauth.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.ccx.services.uiauth.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.ccx.services.uiauth.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{ end }}
