{{- if and .Values.ccx.migrateStores }}
apiVersion: batch/v1
kind: Job
metadata:
  name: ccx-stores-migrate
spec:
  backoffLimit: 0
  template:
    spec:
      initContainers:
        - name: ccx-stores-init
          image: {{ .Values.ccx.services.stores_service.image | default .Values.ccx.backend.image | required "No image set for stores" }}
          command: ["/bin/ccx-stores", "migrate"]
          envFrom:
            - secretRef:
                name: db
      containers:
        - name: stores-migrate
          image: {{ .Values.ccx.services.stores_service.image | default .Values.ccx.backend.image | required "No image set for stores" }}
          command: ["/bin/ccx-stores", "migrate-data"]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PROMETHEUS_URL
              value: http://{{ include "ccx.prometheusHostname" . }}:9090
          {{- with .Values.cmon.id }}
            - name: DEFAULT_CONTROLLER_ID
              value: {{ . }}
          {{- end }}
          {{- range $key, $val := .Values.ccx.services.stores_worker.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: ccx
            - secretRef:
                name: cmon-credentials
            - secretRef:
                name: db
          {{- range $name := .Values.ccx.cloudSecrets }}
            - secretRef:
                name: {{ $name }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: "/conf"
      volumes:
        - name: config
          configMap:
            name: ccx-config
      restartPolicy: Never
    {{- with .Values.ccx.services.storesMigrate.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.ccx.services.storesMigrate.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.ccx.services.storesMigrate.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
