apiVersion: v1
kind: Service
metadata:
  name: ccx-user-svc
  labels:
    app: ccx-user
    run: ccx-user
spec:
  type: ClusterIP
  selector:
    app: ccx-user
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3030
