{{ if not .Values.ccx.newWorld }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ccx-deployer
data:
  {{- with .Values.ccx.services.deployer.config }}
  config.yaml: |
    {{- toYaml . | nindent 4 }}
  {{- end}}
    copy_files:
      - target: "/home/ubuntu/ccx_growfs"
        source: "/etc/ccx-growfs/ccx_growfs.sh"
        perms: "0755"
    {{- if .Values.fluentbit.enabled }}
      - target: "/etc/fluent-bit/fluent-bit.conf"
        source: "/etc/fluent-bit/fluent-bit.conf"
        owner: "root:root"
        perms: "0644"
    {{- end }}
{{ end }}
