apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccx-ui-admin
  labels:
    run: ccx-ui-admin
    app: ccx-ui-admin
spec:
  replicas: {{ .Values.ccx.services.uiadmin.replicas | default 1 }}
  selector:
    matchLabels:
      app: ccx-ui-admin
      run: ccx-ui-admin
  template:
    metadata:
      labels:
        app: ccx-ui-admin
        run: ccx-ui-admin
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/ccx/ccx-ui-admin-config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: ccx-ui-admin
          image: {{ .Values.ccx.services.uiadmin.image | required "No image set for uiadmin" }}
          env:
          {{- range $key, $val := .Values.ccx.services.uiadmin.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          ports:
            - name: service
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.ccx.services.uiadmin.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /usr/share/nginx/html/config.js
            subPath: config.js
            name: ui-admin-config-js-cfg
      {{ with .Values.ccx.services.uiadmin.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.ccx.services.uiadmin.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.ccx.services.uiadmin.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      volumes:
        - name: ui-admin-config-js-cfg
          configMap:
            name: ui-admin-config-js