{{ if .Values.ccx.services.billing.stripe }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: prices
data:
  {{- with .Values.ccx.services.billing.prices }}
  prices.yaml: |
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ end }}