apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccx-rbac-service
  labels:
    app: ccx-rbac-service
    run: ccx-rbac-service
spec:
  replicas: {{ .Values.ccx.services.rbac.replicas | default 1 }}
  selector:
    matchLabels:
      app: ccx-rbac-service
      run: ccx-rbac-service
  template:
    metadata:
      labels:
        app: ccx-rbac-service
        run: ccx-rbac-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        checksum: {{ include (print $.Template.BasePath "/ccx/secrets.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/ccx/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: ccx-rbac-service
          image: {{ .Values.ccx.services.rbac.image | default .Values.ccx.backend.image  | required "No image set for rbac" }}
          command: ["/bin/ccx-rbac-service"]
          env:
          {{- range $key, $val := .Values.ccx.services.rbac.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: ccx
            - secretRef:
                name: db-rbac
          ports:
            - name: service
              containerPort: 19795
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          resources:
            {{- toYaml .Values.ccx.services.rbac.resources | nindent 12 }}
      {{ with .Values.ccx.services.rbac.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.ccx.services.rbac.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.ccx.services.rbac.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{ end }}
