{{ if .Values.ccx.oldWorld }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccx-datastore-storage
  labels:
    app: ccx-datastore-storage
    run: ccx-datastore-storage
spec:
  replicas: {{ .Values.ccx.services.datastorestorage.replicas | default 1 }}
  selector:
    matchLabels:
      app: ccx-datastore-storage
      run: ccx-datastore-storage
  template:
    metadata:
      labels:
        app: ccx-datastore-storage
        run: ccx-datastore-storage
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        checksum: {{ include (print $.Template.BasePath "/ccx/secrets.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/ccx/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: ccx-datastore-storage
          image: {{ .Values.ccx.services.datastorestorage.image | default .Values.ccx.backend.image | required "No image set for datastores" }}
          command: ["/bin/ccx-datastore-storage"]
          env:
            - name: CONFIG_FILE
              value: "/conf/ccx.yaml"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- range $key, $val := .Values.ccx.services.datastorestorage.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: ccx
            - secretRef:
                name: db
          ports:
            - name: service
              containerPort: 19786
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: "/conf"
          resources:
            {{- toYaml .Values.ccx.services.datastorestorage.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: ccx-config
      {{ with .Values.ccx.services.datastorestorage.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.ccx.services.datastorestorage.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.ccx.services.datastorestorage.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{ end }}
{{ end }}
