apiVersion: v1
kind: Service
metadata:
  name: ccx-auth-service-svc
  labels:
    app: ccx-auth-service
    run: ccx-auth-service
spec:
  type: ClusterIP
  selector:
    app: ccx-auth-service
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
