apiVersion: batch/v1
kind: CronJob
metadata:
  name: ccx-billing-updater
spec:
  suspend: false
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
        {{- with .Values.ccx.services.billingupdater.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.ccx.services.billingupdater.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.ccx.services.billingupdater.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          restartPolicy: Never
          containers:
            - name: ccx-billing-updater
              image: {{ .Values.ccx.services.billingupdater.image | default .Values.ccx.backend.image | required "No image set for billing-updater" }}
              command: ["/bin/ccx-billing-updater"]
              env:
              {{- range $key, $val := .Values.ccx.services.billingupdater.env }}
                - name: {{ $key }}
                  value: {{ $val | quote }}
              {{- end }}
              envFrom:
                - configMapRef:
                    name: ccx
                - secretRef:
                    name: db
        {{ if .Values.ccx.services.billing.stripe }}
                - secretRef:
                    name: stripe
              volumeMounts:
                - mountPath: /etc/prices.yaml
                  subPath: prices.yaml
                  name: prices-volume
          volumes:
            - name: prices-volume
              configMap:
                name: prices
          {{ end }}
