apiVersion: batch/v1
kind: CronJob
metadata:
  name: ccx-billing-updater
spec:
  suspend: false
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
        {{- with .Values.ccx.services.billingupdater.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.ccx.services.billingupdater.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.ccx.services.billingupdater.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          restartPolicy: Never
          containers:
            - name: ccx-billing-updater
              image: {{ .Values.ccx.services.billingupdater.image | default .Values.ccx.backend.image | required "No image set for billing-updater" }}
              command: [ "/bin/ccx-billing", "update" ]
              env:
                - name: CONFIG_FILE
                  value: "/conf/ccx.yaml"
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              {{- range $key, $val := .Values.ccx.services.billingupdater.env }}
                - name: {{ $key }}
                  value: {{ $val | quote }}
              {{- end }}
              envFrom:
                - configMapRef:
                    name: ccx
                {{- range $name := .Values.ccx.cloudSecrets }}
                - secretRef:
                    name: {{ $name }}
                {{- end }}
                - secretRef:
                    name: db
                {{- if .Values.ccx.services.billing.stripe }}
                - secretRef:
                    name: stripe
                {{- end }}
              volumeMounts:
                {{- if .Values.ccx.services.billing.stripe }}
                - mountPath: /etc/prices.yaml
                  subPath: prices.yaml
                  name: prices-volume
                {{- end }}
                - name: conf-core
                  mountPath: "/conf/ccx.yaml"
                  subPath: "ccx.yaml"
          volumes:
            {{- if .Values.ccx.services.billing.stripe }}
            - name: prices-volume
              configMap:
                name: prices
            {{- end }}
            - name: conf-core
              configMap:
                name: ccx-config-core
