apiVersion: batch/v1
kind: CronJob
metadata:
  name: ccx-datastores-maintenance
  labels:
    app: ccx-datastores-maintenance
spec:
  suspend: {{ .Values.ccx.env.DISABLE_ROLLBACK | default "false" }}
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: ccx-datastores-maintenance
    spec:
      template:
        metadata:
          labels:
            app: ccx-datastores-maintenance
        spec:
        {{- with .Values.ccx.services.datastorestorage.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.ccx.services.datastorestorage.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.ccx.services.datastorestorage.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          restartPolicy: Never
          containers:
            - name: ccx-datastores-maintenance
              image: {{ .Values.ccx.services.datastorestorage.image | default .Values.ccx.backend.image | required "No image set for datastores" }}
              command: [ "/bin/ccx-datastore-storage", "maintain" ]
              envFrom:
                - configMapRef:
                    name: ccx
