apiVersion: v1
kind: Service
metadata:
  name: ccx-ui-admin-svc
  labels:
    run: ccx-ui-admin
    app: ccx-ui-admin
spec:
  type: ClusterIP
  selector:
    app: ccx-ui-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
