apiVersion: batch/v1
kind: Job
metadata:
  name: ccx-migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "555"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 432000
  template:
    spec:
    {{- with .Values.ccx.services.migrate.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.ccx.services.migrate.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.ccx.services.migrate.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: latest
          image: {{ .Values.ccx.services.migrate.image | required ".Values.ccx.services.migrate.image is missing" }}
          envFrom:
            - secretRef:
                name: db
      restartPolicy: Never
