apiVersion: v1
kind: Service
metadata:
  name: ccx-billing-service-svc
  labels:
    app: ccx-billing-service
    run: ccx-billing-service
spec:
  type: ClusterIP
  selector:
    app: ccx-billing-service
  ports:
    - protocol: TCP
      port: 18077
      targetPort: 18077
