apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccx-admin-service
  labels:
    run: ccx-admin-service
    app: ccx-admin-service
spec:
  replicas: {{ .Values.ccx.services.admin.replicas | default 1 }}
  selector:
    matchLabels:
      app: ccx-admin-service
      run: ccx-admin-service
  template:
    metadata:
      labels:
        app: ccx-admin-service
        run: ccx-admin-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        checksum: {{ include (print $.Template.BasePath "/ccx/secrets.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/ccx/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: ccx-admin-service
          image: {{ .Values.ccx.services.admin.image | default .Values.ccx.backend.image | required "No image set for admin-api" }}
          command: ["/bin/ccx-admin-service"]
          env:
          {{- range $key, $val := .Values.ccx.services.admin.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          {{ if .Values.ccx.newWorld }}
            # new stores enabled
            - name: PREFER_NEW_STORES
              value: "true"
            - name: INCLUDE_NEW_STORES
              value: "true"
          {{ if .Values.ccx.oldWorld }}
            # old stores visible for transition
            - name: INCLUDE_OLD_STORES
              value: "true"
          {{ else }}
            - name: INCLUDE_OLD_STORES
              value: "false"
          {{ end }}
          {{ else }}
            # new stores disabled
            - name: PREFER_NEW_STORES
              value: "false"
            - name: INCLUDE_NEW_STORES
              value: "false"
            - name: INCLUDE_OLD_STORES
              value: "true"
          {{ end }}
          envFrom:
            - configMapRef:
                name: ccx
            - secretRef:
                name: db
            - secretRef:
                name: admin-basic-auth
            {{- range $name := .Values.ccx.services.admin.envFrom }}
            - secretRef:
                name: {{ $name }}
            {{- end }}
          ports:
            - name: service
              containerPort: 19787
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          resources:
            {{- toYaml .Values.ccx.services.admin.resources | nindent 12 }}
      {{ with .Values.ccx.services.admin.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.ccx.services.admin.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.ccx.services.admin.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{ end }}
