apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccx-ui-app
  labels:
    app: ccx-ui-app
    run: ccx-ui-app
spec:
  replicas: {{ .Values.ccx.services.uiapp.replicas | default .Values.global.replicas }}
  selector:
    matchLabels:
      app: ccx-ui-app
      run: ccx-ui-app
  template:
    metadata:
      labels:
        app: ccx-ui-app
        run: ccx-ui-app
    spec:
      containers:
        - name: ccx-ui-app
          image: {{ .Values.ccx.services.uiapp.image | required ".Values.ccx.services.uiapp.image is missing" }}
          env:
          {{- if not .Values.ccx.services.billing.enabled }}
            - name: FE_BILLING_DISABLED
              value: "true"
          {{- end }}
          {{- range $key, $val := .Values.ccx.services.uiapp.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
            - name: FE_BASE_DOMAIN
              value: {{ include "ccx.ccxFQDN" . }}
          ports:
            - name: service
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.ccx.services.uiapp.resources | nindent 12 }}
      {{ with .Values.ccx.services.uiapp.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.ccx.services.uiapp.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.ccx.services.uiapp.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{ end }}
