apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccx-state-worker
  labels:
    app: ccx-state-worker
    run: ccx-state-worker
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ccx-state-worker
      run: ccx-state-worker
  template:
    metadata:
      labels:
        app: ccx-state-worker
        run: ccx-state-worker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        checksum: {{ include (print $.Template.BasePath "/ccx/secrets.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/ccx/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: state-worker
          image: {{ .Values.ccx.services.datastorestorage.image | default .Values.ccx.backend.image | required "No image set for state-worker" }}
          command: [ "/bin/ccx-datastore-storage" ]
          args:
            - state-worker
          env:
            - name: CONFIG_FILE
              value: "/conf/ccx.yaml"
          {{- range $key, $val := .Values.ccx.services.datastorestorage.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- if .Values.ccx.services.datastorestorage.workInterval }}
            - name: WORK_INTERVAL
              value : {{ .Values.ccx.services.datastorestorage.workInterval | quote }}
          {{- end }}
          {{- if .Values.ccx.autoRepair.enabled }}
            - name: AUTO_REPAIR_ENABLED
              value : "true"
            - name: AUTO_REPAIR_AFTER
              value : {{ .Values.ccx.autoRepair.delay | quote }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: ccx
            - secretRef:
                name: db
            {{ if not .Values.ccx.useK8sSecrets }}
            - secretRef:
                name: vault
            {{ end }}
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: "/conf"
          resources:
            {{- toYaml .Values.ccx.services.datastorestorage.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: ccx-config
      {{ with .Values.ccx.services.datastorestorage.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.ccx.services.datastorestorage.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.ccx.services.datastorestorage.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{ end }}
