{{ if not .Values.ccx.newWorld }}
apiVersion: v1
kind: Service
metadata:
  name: ccx-deployer-service-svc
  labels:
    app: ccx-deployer-service
    run: ccx-deployer-service
  annotations:
    {{- range $key, $val := .Values.ccx.services.deployer.serviceAnnotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  type: {{ .Values.ccx.services.deployer.serviceType | default "ClusterIP" }}
  selector:
    app: ccx-deployer-service
  ports:
    - protocol: TCP
      port: 19309
      targetPort: 19309
{{ end }}
