{{ if .Values.ccx.services.cmonproxy.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cmon-proxy-ingress
  annotations:
    {{ if .Values.ccx.ingress.ssl.clusterIssuer }}
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: {{ .Values.ccx.ingress.ssl.clusterIssuer }}
    {{ end }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/secure-backends: "true"
spec:
  ingressClassName: {{ .Values.ccx.ingress.ingressClassName | default "nginx" }}
  tls:
    - hosts:
        - ccx-mgmt.{{ include "ccx.sessionDomain" . }}
      secretName: {{ .Values.ccx.ingress.ssl.secretName | default "cmon-proxy-cert" }}
  rules:
    - host: ccx-mgmt.{{ include "ccx.sessionDomain" . }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: cmon-proxy-svc
                port:
                  number: 19051
{{ end }}