apiVersion: v1
kind: ConfigMap
metadata:
  name: ccx
data:
  # this should be essentially static after the cluster is created - mutable config is in other places
  SESSION_DOMAIN: {{ include "ccx.sessionDomain" . }}
  CROSS_ORIGINS: {{ .Values.crossOrigins | join "," | quote }}
  {{- if .Values.ccx.userDomain }}
  USER_DOMAIN: {{ .Values.ccx.userDomain }}
  {{- end }}
  AFFILIATION: {{ .Values.ccx.affiliation | default "ccx" | quote }}
  SERVICE_URL_PREFIX: https://{{ include "ccx.ccxFQDN" . }}
  APP_URL: https://{{ include "ccx.ccxFQDN" . }}
  AUTH_URL: https://{{ include "ccx.ccxFQDN" . }}/auth
  NATS_SERVER: {{ .Values.ccx.nats.server | default "ccx-nats" | quote }}
  NATS_CLUSTER_ID: {{ .Values.ccx.nats.clusterID | default "test-cluster" | quote }}
  GIN_MODE: release
  # billing service and billing updater
  {{- if .Values.ccx.services.billing.enabled }}
  BILLING_IMPLIED_SUBSCRIPTION: "0"
  CCX_BILLING_NETWORK: "true"
  CCX_BILLING_STORAGE: "true"
  {{- else }}
  BILLING_IMPLIED_SUBSCRIPTION: "1"
  {{- end }}
  {{- if .Values.ccx.newWorld }}
  DEPLOYER_ADDR: ccx-stores-svc:20002
  VPC_STORAGE_ADDR: ccx-stores-svc:20002
  {{- end }}
  {{- range $key, $val := .Values.ccx.env }}
  {{ $key }} : {{ $val | quote }}
  {{- end }}
  {{- if .Values.ccx.useK8sSecrets }}
  SECRETS_USE_K8S: "true"
  {{- end }}