{{ if .Values.ccx.createRBAC }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin
rules:
- apiGroups: ["*", ""]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-binding
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io
{{ end }}