{{ if .Values.ccx.createRBAC }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service
rules:
- apiGroups: ["*", ""]
  resources: ["services"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-binding
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: service
  apiGroup: rbac.authorization.k8s.io
{{ end }}