apiVersion: v1
kind: Secret
metadata:
  name: db
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "111"
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  DB_DSN: postgres://{{ include "ccx.db.username" . }}:{{ include "ccx.db.password" . }}@{{ include "ccx.db.address" . }}:{{ include "ccx.db.port" . }}/ccx?sslmode=disable
---
apiVersion: v1
kind: Secret
metadata:
  name: db-backup
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "111"
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  DB_DSN: postgres://{{ include "ccx.db.username" . }}:{{ include "ccx.db.password" . }}@{{ include "ccx.db.address" . }}:{{ include "ccx.db.port" . }}/ccx_backup?sslmode=disable
---
apiVersion: v1
kind: Secret
metadata:
  name: db-user
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "111"
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  DB_DSN: postgres://{{ include "ccx.db.username" . }}:{{ include "ccx.db.password" . }}@{{ include "ccx.db.address" . }}:{{ include "ccx.db.port" . }}/userdb?sslmode=disable
---
apiVersion: v1
kind: Secret
metadata:
  name: db-deployer
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "111"
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  DB_DSN: postgres://{{ include "ccx.db.username" . }}:{{ include "ccx.db.password" . }}@{{ include "ccx.db.address" . }}:{{ include "ccx.db.port" . }}/ccx_deployer?sslmode=disable
---
apiVersion: v1
kind: Secret
metadata:
  name: db-notification
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "111"
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  DB_DSN: postgres://{{ include "ccx.db.username" . }}:{{ include "ccx.db.password" . }}@{{ include "ccx.db.address" . }}:{{ include "ccx.db.port" . }}/ccx_notification?sslmode=disable
---
apiVersion: v1
kind: Secret
metadata:
  name: db-projects
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "111"
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  DB_DSN: postgres://{{ include "ccx.db.username" . }}:{{ include "ccx.db.password" . }}@{{ include "ccx.db.address" . }}:{{ include "ccx.db.port" . }}/ccx_projects?sslmode=disable
---
apiVersion: v1
kind: Secret
metadata:
  name: db-rbac
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "111"
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  DB_DSN: postgres://{{ include "ccx.db.username" . }}:{{ include "ccx.db.password" . }}@{{ include "ccx.db.address" . }}:{{ include "ccx.db.port" . }}/ccx_rbac?sslmode=disable
---
apiVersion: v1
kind: Secret
metadata:
  name: db-vpc
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "111"
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  DB_DSN: postgres://{{ include "ccx.db.username" . }}:{{ include "ccx.db.password" . }}@{{ include "ccx.db.address" . }}:{{ include "ccx.db.port" . }}/ccx_vpc?sslmode=disable
---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "111"
    "helm.sh/resource-policy": keep
type: Opaque
data:
  VAULT_ADDR: {{ .Values.ccx.vault.addr | default "http://ccxdeps-vault:8200" | b64enc }}
  VAULT_TOKEN: {{ .Values.ccx.vault.token | default "root" | b64enc }}
  {{- range $key, $val := .Values.ccx.vault.env }}
  {{ $key }} : {{ $val | toString | b64enc }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-stores
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "111"
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  DB_DSN: postgres://{{ include "ccx.db.username" . }}:{{ include "ccx.db.password" . }}@{{ include "ccx.db.address" . }}:{{ include "ccx.db.port" . }}/ccx_stores?sslmode=disable
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-basic-auth
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "111"
    "helm.sh/resource-policy": keep
type: Opaque
data:
  ADMIN_AUTH_USERNAME: {{ include "ccx.services.admin.basicauth.username" . | b64enc }}
  ADMIN_AUTH_PASSWORD: {{ include "ccx.services.admin.basicauth.password" . | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-users
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "111"
    "helm.sh/resource-policy": keep
type: Opaque
data:
  ADMIN_USERS: {{ include "ccx.admin.users" . | b64enc}}