apiVersion: v1
kind: Service
metadata:
  name: store-metrics-sd-svc
  labels:
    app: store-metrics-sd
    run: store-metrics-sd
spec:
  type: ClusterIP
  selector:
    app: store-metrics-sd
    run: store-metrics-sd
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
