apiVersion: v1
kind: Secret
stringData:
  cmon-user: {{ .Values.cmon.user | required "cmon.user is required" }}
  cmon-password: {{ .Values.cmon.password | required "cmon.password is required" }}
type: Opaque
metadata:
  name: cmon-credentials
{{ if .Values.cmon.license }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cmon-license
data:
  CMON_LICENSE: {{ .Values.cmon.license | required ".Values.cmon.license is required" }}
  license: {{ .Values.cmon.license | required ".Values.cmon.license is required" }}
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: s9s-conf
stringData:
  s9s.conf: |
    [global]
    controller=https://cmon-master:9501/
    cmon_user={{ .Values.cmon.user | required "cmon.user is required" }}
    cmon_password={{ .Values.cmon.password | required "cmon.password is required" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cmon-cnf
stringData:
  cmon.cnf: |
    hostname=0.0.0.0
    mysql_hostname={{ .Values.cmon.db.host }}
    mysql_port={{ .Values.cmon.db.port }}
    mysql_password='{{ .Values.cmon.db.password }}'
    cmon_user={{ .Values.cmon.db.user }}
    cmon_db={{ .Values.cmon.db.name }}
    rpc_user={{ include "cmonUser" . }}
    rpc_key={{ include "cmonPassword" .}}
    controller_id={{ .Values.cmon.id }}
    prometheus_hostname={{ .Values.prometheusHostname }}

---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-keys
stringData:
{{ (.Files.Glob "files/ssh-keys/*").AsConfig | indent 2 }}