{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace "cmon-credentials" }}
{{- $existingConfigMap := lookup "v1" "ConfigMap" .Release.Namespace "config-js" }}
{{- $existingCcsetupSecret := lookup "v1" "Secret" .Release.Namespace "cmon-ccsetup" }}
{{- $randomPassword := "" }}
{{- $ccsetupRandomPassword := "" }}

{{/* Preserve passwords during upgrades */}}
{{- if .Values.cmon.password }}
  {{- $randomPassword = .Values.cmon.password }}
{{- else if $existingSecret }}
  {{- $randomPassword = index $existingSecret.data "cmon-password" | b64dec }}
{{- else }}
  {{- $randomPassword = (randAlpha 16) }}
{{- end }}

{{- if $existingCcsetupSecret }}
  {{- $ccsetupRandomPassword = index $existingCcsetupSecret.data "ccsetup-password" | b64dec }}
{{- else }}
  {{- $ccsetupRandomPassword = (randAlpha 16) }}
{{- end }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cmon-credentials
stringData:
  cmon-user: {{ or .Values.cmon.user | default "ccrpc" }}
  cmon-password: {{ or .Values.cmon.password $randomPassword }}

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cmon-ccsetup
stringData:
  ccsetup-password: {{ $ccsetupRandomPassword }}

{{ if .Values.cmon.license }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cmon-license
stringData:
  CMON_LICENSE: {{ .Values.cmon.license | required ".Values.cmon.license is required" }}
  license: {{ .Values.cmon.license | required ".Values.cmon.license is required" }}
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: s9s-conf
stringData:
  s9s.conf: |
    [global]
    controller=https://cmon-master:9501/
    cmon_user={{ or .Values.cmon.user | default "ccrpc" }}
    cmon_password={{ or .Values.cmon.password $randomPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cmon-cnf
stringData:
  cmon.cnf: |
    hostname=0.0.0.0
    ccx_mode=true
    cmondb_hostname={{ .Values.cmon.db.host | default .Release.Name }}
    cmondb_port={{ .Values.cmon.db.port | default 3306 }}
    cmondb_password='{{ .Values.cmon.db.password | default "cmon" }}'
    cmon_user={{ .Values.cmon.db.user | default "cmon" }}
    cmon_db={{ .Values.cmon.db.name | default "cmon" }}
    rpc_user={{ or .Values.cmon.user | default "ccrpc" }}
    rpc_key={{ or .Values.cmon.password $randomPassword }}
    ccsetup_key={{ $ccsetupRandomPassword }}
    controller_id={{ .Values.cmon.id }}
    prometheus_hostname={{ default (printf "%s-monitoring-server" .Release.Name) .Values.prometheusHostname }}

---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-keys
stringData:
{{ (.Files.Glob "files/ssh-keys/*").AsConfig | indent 2 }}

# below config map is here so it can share a randomly generated password
# unfortunately helm supports this only if random string is used in one template
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-js
data:
  config.js: |
    window.FEAS_ENV = {
      CMON_API_URL: '/cmon/v2',
      VERSION: '{{ splitList ":" (include "cc.cmonImage" .) | last }}',
      INITIAL_PASSWORD: '{{ $ccsetupRandomPassword }}',
      USER_REGISTRATION: 1,
    };