{{/* Code generated by gen-intent-metadata; DO NOT EDIT. */}}
{{- define "agent-operator.intentResources" -}}
["appbundles","appbundles/finalizers","appbundles/status","databasebackups","databasebackups/finalizers","databasebackups/status","databasebackupschedules","databasebackupschedules/finalizers","databasebackupschedules/status","databaseclusters","databaseclusters/finalizers","databaseclusters/status","databaseoperators","databaseoperators/finalizers","databaseoperators/status","deliveryconfigs","deliveryconfigs/finalizers","deliveryconfigs/status","deliveryrequests","deliveryrequests/finalizers","deliveryrequests/status"]
{{- end -}}
