{{- if .Values.cleanup.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "agent-operator.fullname" . }}-cleanup-phase1-databaseclusters
  namespace: {{ include "agent-operator.namespace" . }}
  labels:
    {{- include "agent-operator.labels" . | nindent 4 }}
    cleanup-phase: "1"
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  activeDeadlineSeconds: {{ .Values.cleanup.timeoutSeconds }}
  template:
    metadata:
      labels:
        cleanup-phase: "1"
        {{- include "agent-operator.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "agent-operator.serviceAccountName" . }}
      containers:
      - name: cleanup-databaseclusters
        image: "{{ .Values.cleanup.image.repository }}:{{ .Values.cleanup.image.tag }}"
        imagePullPolicy: {{ .Values.cleanup.image.pullPolicy }}
        resources:
          {{- toYaml .Values.cleanup.resources | nindent 10 }}
        command:
        - /bin/bash
        - -c
        - |
          set -e
          echo "Phase 1: Cleaning up DatabaseClusters..."
          
          # Check if CRD exists before attempting to delete resources
          if kubectl get crd databaseclusters.agent.severalnines.com >/dev/null 2>&1; then
            echo "Found DatabaseClusters CRD, proceeding with cleanup..."
            
            # Get all DatabaseClusters across all namespaces
            clusters=$(kubectl get databaseclusters.agent.severalnines.com --all-namespaces -o jsonpath='{range .items[*]}{.metadata.namespace}{" "}{.metadata.name}{"\n"}{end}' 2>/dev/null || true)
            
            if [ -n "$clusters" ]; then
              echo "Found DatabaseClusters to delete:"
              echo "$clusters"
              
              # Delete each DatabaseCluster
              echo "$clusters" | while IFS=' ' read -r namespace name; do
                if [ -n "$namespace" ] && [ -n "$name" ]; then
                  echo "Deleting DatabaseCluster $name in namespace $namespace..."
                  kubectl delete databasecluster.agent.severalnines.com "$name" -n "$namespace" --timeout=60s || true
                fi
              done
              
              # Wait for all DatabaseClusters to be deleted
              echo "Waiting for all DatabaseClusters to be deleted..."
              for i in {1..30}; do
                remaining=$(kubectl get databaseclusters.agent.severalnines.com --all-namespaces --no-headers 2>/dev/null | wc -l || echo "0")
                if [ "$remaining" -eq 0 ]; then
                  echo "All DatabaseClusters deleted successfully"
                  break
                fi
                echo "Waiting for $remaining DatabaseClusters to be deleted... (attempt $i/30)"
                sleep 10
              done
            else
              echo "No DatabaseClusters found to delete"
            fi
          else
            echo "DatabaseClusters CRD not found, skipping cleanup"
          fi
          
          echo "Phase 1 cleanup completed"
{{- end }} 