{{- if and .Values.metrics.enabled .Values.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-operator.fullname" . }}-metrics
  namespace: {{ include "agent-operator.namespace" . }}
  labels:
    {{- include "agent-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metrics.service.type }}
  selector:
    control-plane: controller-manager
    {{- include "agent-operator.selectorLabels" . | nindent 4 }}
  ports:
  - name: metrics
    port: {{ .Values.metrics.port }}
    targetPort: metrics
    protocol: TCP
{{- end }}
