{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "agent-operator.fullname" . }}-manager-role
  labels:
    {{- include "agent-operator.labels" . | nindent 4 }}
rules:
# Allow the operator to manage its own CRDs
- apiGroups: ["agent.severalnines.com"]
  resources: ["databaseclusters", "databaseoperators", "databasebackups", "databasebackupschedules"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

- apiGroups: ["agent.severalnines.com"]
  resources: ["databaseclusters/status", "databaseoperators/status", "databasebackups/status", "databasebackupschedules/status"]
  verbs: ["get", "patch", "update"]

- apiGroups: ["agent.severalnines.com"]
  resources: ["databaseclusters/finalizers", "databaseoperators/finalizers", "databasebackups/finalizers", "databasebackupschedules/finalizers"]
  verbs: ["update"]

# Core API permissions
- apiGroups: [""]
  resources: ["configmaps", "secrets", "services", "persistentvolumeclaims", "events", "pods", "pods/log", "namespaces"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

# App API permissions
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

# Batch API permissions
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

# Allow access to nodes
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]

# Wildcard permission for all other API groups (including database operators)
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
{{- end }} 