{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "agent-operator.fullname" . }}-manager-rolebinding
  labels:
    {{- include "agent-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "agent-operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "agent-operator.serviceAccountName" . }}
  namespace: {{ include "agent-operator.namespace" . }}
{{- end }} 