{{- if .Values.agent.publicKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: agent-credentials
  namespace: {{ include "agent-operator.namespace" . }}
  labels:
    {{- include "agent-operator.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  public_key: {{ .Values.agent.publicKey }}
  registered: "false"
{{- end -}} 