{{- $secretName := "agent-credentials" }}
{{- $namespace := include "agent-operator.namespace" . }}
{{- $existingSecret := lookup "v1" "Secret" $namespace $secretName }}

{{- if not $existingSecret }}
  {{- /* Only define the Secret if it does not already exist */}}
  {{- if .Values.agent.publicKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "agent-operator.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    # This will keep secret from being deleted on helm uninstall
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  public_key: {{ .Values.agent.publicKey }}
  registered: "false"
  {{- end }}
{{- end }} 