{{- $secretName := "agent-credentials" }}
{{- $namespace := include "agent-operator.namespace" . }}
{{- $existingSecret := lookup "v1" "Secret" $namespace $secretName }}

{{- if not $existingSecret }}
  {{- /* Secret does not exist. Create it IF .Values.agent.publicKey is provided. */}}
  {{- if .Values.agent.publicKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "agent-operator.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  public_key: {{ .Values.agent.publicKey }}
  registered: "false"
  {{- /* Other fields like agent_id, agent_private_key, agent_public_key will be added by the agent */}}
  {{- end }}
{{- else }}
  {{- /* Secret exists. Manage its metadata but preserve its existing data. */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "agent-operator.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
{{- /* Use the existing data from the live secret */}}
data:
  {{- range $key, $val := $existingSecret.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }} 