apiVersion: v2
name: ccx-monitoring
description: An Umbrella Chart for observability components in CCX

type: application

## version
version: 0.6.0
appVersion: "0.6.0"

dependencies:
  - name: victoria-metrics-single
    repository: https://victoriametrics.github.io/helm-charts/
    version: 0.9.14
    condition: victoria-metrics-single.enabled
  - name: victoria-metrics-alert
    repository: https://victoriametrics.github.io/helm-charts/
    version: 0.8.6
    condition: victoria-metrics-alert.enabled
  - name: victoria-metrics-agent
    repository: https://victoriametrics.github.io/helm-charts/
    version: 0.9.15
    condition: victoria-metrics-agent.enabled
  - name: kube-state-metrics
    repository: https://prometheus-community.github.io/helm-charts
    version: 5.16.0
    condition: kube-state-metrics.enabled
  - name: alertmanager
    repository: https://prometheus-community.github.io/helm-charts
    version: 1.7.0
    condition: alertmanager.enabled
  - name: grafana
    repository: https://grafana.github.io/helm-charts
    version: 7.0.1
    condition: grafana.enabled
  - name: loki
    repository: https://grafana.github.io/helm-charts
    version: 6.5.2
    condition: loki.enabled
  - name: prometheus-node-exporter
    repository: https://prometheus-community.github.io/helm-charts
    version: 4.23.2
    condition: node-exporter.enabled
  - name: prometheus-blackbox-exporter
    repository: https://prometheus-community.github.io/helm-charts
    version: 8.4.0
    condition: prometheus-blackbox-exporter.enabled
