{
 "title": "MSSQL dashboard",
 "description": "Performance and health metrics for Prometheus MSSQL Exporter running on docker.",
 "tags": [
  "prometheus",
  "SQL Server"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "up" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "up{job=\"$job\"}"
   },
   {
    "name": "database_name",
    "query": "mssql_connections{instance=\"$instance\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Databases properties",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DATABASES HEALTH",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssql_up{instance=\"$instance\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "State OFFLINE",
     "query": "SELECT mean(\"total\") FROM \"State OFFLINE\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "stat",
   "description": "Number of lock requests per second that resulted in a deadlock since last restart",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssql_deadlocks{instance=\"$instance\"}",
     "measurement": "State ONLINE",
     "query": "SELECT \"total\" FROM \"State ONLINE\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "Kill Connection Errors",
   "type": "stat",
   "description": "Number of kill connection errors/sec since last restart",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssql_kill_connection_errors{instance=\"$instance\"}",
     "measurement": "State OFFLINE",
     "query": "SELECT \"total\" FROM \"State OFFLINE\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "Number of Transact-SQL",
   "type": "stat",
   "description": "Number of Transact-SQL command batches received per second. This statistic is affected by all constraints (such as I/O, number of users, cachesize, complexity of requests, and so on). High batch requests mean good throughput",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssql_batchrequestpersecond{instance=\"$instance\"}",
     "measurement": "State RECOVERING",
     "query": "SELECT \"total\" FROM \"State RECOVERING\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "Number of page faults",
   "type": "stat",
   "description": "Number of page faults since last restart",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssql_page_fault_count{instance=\"$instance\"}",
     "legendFormat": "Page Fault Count",
     "measurement": "State RECOVERY_PENDING",
     "query": "SELECT \"total\" FROM \"State RECOVERY_PENDING\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Physical memory",
   "type": "stat",
   "description": "Total physical memory",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssql_total_physical_memory_kb{instance=\"$instance\"} / 1024",
     "measurement": "Performance metrics",
     "query": "SELECT \"Point In Time Recovery\" FROM \"Performance metrics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance metrics' AND $timeFilter",
     "select": [
      [
       { "params": [ "Point In Time Recovery" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance metrics" }
     ]
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "stat",
   "description": "Available physical memory",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssql_available_physical_memory_kb{instance=\"$instance\"} / 1024",
     "measurement": "Recovery Model FULL",
     "query": "SELECT \"total\" FROM \"Recovery Model FULL\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "description": "Number of active connections",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mssql_connections{instance=\"$instance\",db_name=\"$database_name\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Active Connections",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "User Errors",
   "type": "graph",
   "description": "Number of user errors/sec since last restart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mssql_user_errors{instance=\"$instance\"}",
     "legendFormat": "User errors"
    }
   ]
  },
  {
   "title": "Write Stall Time (ms)",
   "type": "graph",
   "description": "Wait time (ms) of stall since last restart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms", "label": "Stall time" }
   ],
   "targets": [
    {
     "expr": "mssql_io_write_stall{instance=\"$instance\",name=\"$database_name\"}",
     "legendFormat": "Write Stall Time"
    }
   ]
  },
  {
   "title": "Read Stall Time (ms)",
   "type": "graph",
   "description": "Wait time (ms) of stall since last restart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ms", "label": "Stall time" }
   ],
   "targets": [
    {
     "expr": "mssql_io_read_stall{instance=\"$instance\",name=\"$database_name\"}",
     "legendFormat": "Read Stall Time"
    }
   ]
  },
  {
   "title": "Write Queue Stall Time (ms)",
   "type": "graph",
   "description": "Wait time (ms) of stall since last restart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms", "label": "Stall time" }
   ],
   "targets": [
    {
     "expr": "mssql_io_queued_write_stall{instance=\"$instance\",name=\"$database_name\"}",
     "legendFormat": "Queued Write Stall Time"
    }
   ]
  },
  {
   "title": "Read Queue Stall Time (ms)",
   "type": "graph",
   "description": "Wait time (ms) of stall since last restart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ms", "label": "Stall time" }
   ],
   "targets": [
    {
     "expr": "mssql_io_queued_read_stall{instance=\"$instance\",name=\"$database_name\"}",
     "legendFormat": "Queued Read Stall Time"
    }
   ]
  }
 ]
}