{{ if ( and .Values.cmon .Values.cmon.enabled ) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ccx.name" . }}-cmon-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    {{ if .Values.ccx.ingress.ssl.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ccx.ingress.ssl.clusterIssuer }}
    {{ end }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: {{ .Values.ccx.ingress.ingressClassName | default "nginx" }}
  tls:
    - hosts:
        - {{ include "ccx.ccFQDN" . }}
      secretName: {{ include "ccx.ccFQDN" . }}
  rules:
    - host: {{ include "ccx.ccFQDN" . }}
      http:
        paths:
          - backend:
              service:
                name: cmon-master
                port:
                  number: 3000 #ccv2
            path: /(.*)
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ccx.name" . }}-cmon-ingress-ssl
  annotations:
    kubernetes.io/tls-acme: "true"
    {{ if .Values.ccx.ingress.ssl.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ccx.ingress.ssl.clusterIssuer }}
    {{ end }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: {{ .Values.ccx.ingress.ingressClassName | default "nginx" }}
  tls:
    - hosts:
        - {{ include "ccx.ccFQDN" . }}
      secretName: {{ include "ccx.ccFQDN" . }}
  rules:
    - host: {{ include "ccx.ccFQDN" . }}
      http:
        paths:
          - backend:
              service:
                name: cmon-master #cmon
                port:
                  number: 9501
            path: /cmon/(.*)
            pathType: ImplementationSpecific
{{ end }}