apiVersion: v1
kind: Secret
stringData:
  cmon-user: {{ include "ccx.cmonUser" . }}
  cmon-password: {{ include "ccx.cmonPassword" . }}
type: Opaque
metadata:
  name: cmon-credentials
{{ if .Values.cmon.license }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cmon-license
data:
  CMON_LICENSE: {{ .Values.cmon.license | required ".Values.cmon.license is required" }}
  license: {{ .Values.cmon.license | required ".Values.cmon.license is required" }}
{{ end }}
{{ if ( and .Values.cmon .Values.cmon.enabled ) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: s9s-conf
stringData:
  s9s.conf: |
    [global]
    controller=https://cmon-master:9501/
    cmon_user={{ include "ccx.cmonUser" . }}
    cmon_password={{ include "ccx.cmonRPCKey" . }}
    [log]
    brief_job_log_format="%T %36B:%-5L: %-7S %M\n"
    brief_log_format="%C %36B:%-5L: %-8S %M\n"
---
apiVersion: v1
kind: Secret
metadata:
  name: cmon-cnf
stringData:
  cmon.cnf: |
    hostname=0.0.0.0
    ccx_mode=true
    cmondb_hostname={{ include "ccx.cmonDbHost" . }}
    cmondb_port={{ include "ccx.cmonDbPort" . }}
    cmondb_password='{{ include "ccx.cmonDbPassword" . }}'
    cmon_user={{ include "ccx.cmonDbUser" . }}
    cmon_db={{ include "ccx.cmonDbName" . }}
    rpc_user={{ include "ccx.cmonUser" . }}
    rpc_key={{ include "ccx.cmonPassword" . }}
    controller_id={{ .Values.cmon.id }}
    prometheus_hostname={{ include "ccx.prometheusHostname" . }}
{{ end }}
