{{ if ( and .Values.cmon .Values.cmon.enabled ) }}
apiVersion: v1
kind: Service
metadata:
  name: cmon-master
  labels:
    app: cmon-master
    run: cmon-master
spec:
  ports:
  - port: 9501
    protocol: TCP
    targetPort: 9501
    name: 9501-port
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: 8080-port
  - port: 9954
    protocol: TCP
    targetPort: 9954
    name: 9954-port
  - port: 80
    protocol: TCP
    targetPort: 80
    name: 80-port
  - port: 9511
    protocol: TCP
    targetPort: 9511
    name: 9511-port
  selector:
    app: cmon-master
    run: cmon-master
  type: ClusterIP
{{ end }}