ccx:
  # list of k8s secrets containing cloud credentials
  # if this is not set, ccx will start but you won't be able to deploy anything
  cloudSecrets:
   - openstack #this have to exist in k8s secrets! - see secrets-template.yaml
  config:
    clouds:
    - code: mycloud
      name: MyCloud    
      instance_types:
      - code: m1.small
        cpu: 2
        disk_size: 60
        name: Small
        ram: 4
        type: m1.small
      network_types:
      - code: public
        in_vpc: false
        info: All instances will be deployed with public IPs. Access to the public IPs is controlled by a firewall.
        name: Public
      regions:
      - availability_zones:
        - code: nova
          name: MyAZ
        city: Stockholm
        code: my-region1
        continent_code: EU
        country_code: SE
        display_code: my-region1
        name: Stockholm
  services:
    deployer:
      config:
        openstack_vendors:
          mycloud:
            floating_network_id: MY_FLOATING_NETWORK_ID
            network_api_version: NetworkNeutron
            network_id: MY_NETWORK_ID
            project_id: MY_PROJECT_ID
            regions:
              my-region1:
                image_id: MY_IMAGE_ID
                # The secgrp_name refers to the security group name which will be used by ccx to access the datastore VMs.
                # It should be created manually beforehand and allow all TCP traffic from all k8s nodes where ccx is running.
                secgrp_name: ccx-common
