ccxFQDN: ccx.example.com
ccFQDN: cc.example.com
cc:
  cidr: 0.0.0.0/0
ccx:
  # List of Kubernetes secrets containing cloud credentials.
  cidr: 0.0.0.0/0
  # List of Kubernetes secrets containing cloud credentials.
  cloudSecrets:
    - openstack  # This secret must exist in Kubernetes. See 'secrets-template.yaml' for reference.
    - openstack-s3 # This secret must exist in Kubernetes. See 'secrets-template.yaml' for reference.
  config:
    clouds:
      - code: mycloud  # Unique code for your cloud provider
        name: MyCloud  # Human-readable name
        instance_types:
          - code: m1.small  # Instance code; must match your cloud provider
            name: Small     # Display name
            cpu: 2          # Number of vCPUs. Minimum 2 vcpus for test
            ram: 4          # RAM in GB. Minimum 4GB for test
            disk_size: 60   # Min. disk size in GB for the database. This is not the size of the system/root disk.
            type: m1.small  # Cloud provider's type or flavor name

        network_types:
          - code: public
            name: Public
            in_vpc: false
            info: >
              All instances will be deployed with public IPs.
              Access to the public IPs is controlled by a firewall.

        regions:
          - code: my-region1
            display_code: my-region1
            name: Stockholm
            city: Stockholm
            country_code: SE
            continent_code: EU
            availability_zones:
              - code: nova
                name: MyAZ

  services:
    deployer:
      config:
        openstack_vendors:
          mycloud:
            floating_network_id: MY_FLOATING_NETWORK_ID  # Replace with actual ID, e.g., "12345-abcde"
            #public_pool: MY_FLOATING_NETWORK_ID # Enable this if a public pool is used, same value as floating_network_id.
            network_api_version: NetworkNeutron          # Typically "NetworkNeutron"
            network_id: MY_NETWORK_ID                    # Replace with actual network ID
            project_id: MY_PROJECT_ID                    # Replace with your OpenStack project ID
            regions:
              my-region1:
                image_id: MY_IMAGE_ID                    # Replace with image ID for the region
                # secgrp_name refers to the security group name used by ccx to access datastore VMs.
                # It must be created manually and allow all TCP traffic from all Kubernetes nodes where ccx is running.
                secgrp_name: ccx-common                  # Recommended to use a dedicated security group

# NOTES:
# - Replace all 'MY_*' placeholders with actual values from your OpenStack environment.
# - Validate all IDs (network, image, project) before deployment to prevent errors.
# - Use a YAML linter to check for syntax or formatting issues.
# - For security, avoid committing real credentials or sensitive information.
