sessionDomain: ccx.mycloud.com
ccxFQDN: ccx.mycloud.com
ccx:
  # list of k8s secrets containing cloud credentials
  # if this is not set, ccx will start but you won't be able to deploy anything
  cloudSecrets:
   - aws