---
apiVersion: v1
kind: Secret
metadata:
  name: aws
type: Opaque
data:
  AWS_ACCESS_KEY_ID: CHANGE_ME
  AWS_SECRET_ACCESS_KEY: CHANGE_ME
---
apiVersion: v1
kind: Secret
metadata:
  name: openstack
type: Opaque
data:
  MYCLOUD_AUTH_URL: YOUR
  MYCLOUD_PASSWORD: OPENSTACK
  MYCLOUD_PROJECT_ID: CREDENTIALS
  MYCLOUD_USER_DOMAIN: HERE
  MYCLOUD_USERNAME: AND_HERE
  MYCLOUD_USER_DOMAIN_NAME: HERE # duplicates USER_DOMAIN
---
apiVersion: v1
kind: Secret
metadata:
  name: openstack-s3
type: Opaque
data:
  MYCLOUD_S3_ENDPOINT: CHANGE_ME
  MYCLOUD_S3_ACCESSKEY: CHANGE_ME
  MYCLOUD_S3_SECRETKEY: CHANGE_ME
  MYCLOUD_S3_BUCKETNAME: CHANGE_ME
  MYCLOUD_S3_INSECURE_SSL: ZmFsc2U= # base64 encoded 'true' or 'false'
---
apiVersion: v1
kind: Secret
metadata:
  name: gcp
type: Opaque
data:
  GCP_CREDENTIALS: CHANGE_ME # base64 encoded json of the service account file
  GCP_PROJECT_ID: CHANGE_ME # base64 encoded of the project id to use for GCP
---
apiVersion: v1
kind: Secret
metadata:
  name: gcp-s3
type: Opaque
data:
  GCP_S3_ACCESSKEY: CHANGE_ME
  GCP_S3_SECRETKEY: CHANGE_ME
  GCP_S3_BUCKETNAME: CHANGE_ME
---
apiVersion: v1
kind: Secret
metadata:
  name: smtp
type: Opaque
data:
  SMTP_HOST: CHANGE_ME
  SMTP_PORT: "CHANGE_ME"
  SMTP_USERNAME: CHANGE_ME
  SMTP_PASSWORD: CHANGE_ME
  SMTP_FROM: change@me.net
  SMTP_FROM_NAME: CCX
