---
apiVersion: v1
kind: Secret
metadata:
  name: mycloud-openstack
type: Opaque
data:
  MYCLOUD_AUTH_URL: YOUR
  MYCLOUD_PASSWORD: OPENSTACK
  MYCLOUD_PROJECT_ID: CREDENTIALS
  MYCLOUD_USER_DOMAIN: HERE
  MYCLOUD_USERNAME: AND_HERE_BASE64_ENCODED_EVERYWHERE
  MYCLOUD_USER_DOMAIN_NAME: HERE # duplicates USER_DOMAIN
---
apiVersion: v1
kind: Secret
metadata:
  name: mycloud-s3
type: Opaque
data:
  MYCLOUD_S3_ENDPOINT: CHANGE_ME_BASE64_ENCODED
  MYCLOUD_S3_ACCESSKEY: CHANGE_ME_BASE64_ENCODED
  MYCLOUD_S3_SECRETKEY: CHANGE_ME_BASE64_ENCODED
  MYCLOUD_S3_BUCKETNAME: CHANGE_ME_BASE64_ENCODED
  MYCLOUD_S3_INSECURE_SSL: ZmFsc2U= # base64 encoded 'true' or 'false'
